// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub usdtcontract_added_black_lists: ::prost::alloc::vec::Vec<
        UsdtcontractAddedBlackList,
    >,
    #[prost(message, repeated, tag = "2")]
    pub usdtcontract_approvals: ::prost::alloc::vec::Vec<UsdtcontractApproval>,
    #[prost(message, repeated, tag = "3")]
    pub usdtcontract_deprecates: ::prost::alloc::vec::Vec<UsdtcontractDeprecate>,
    #[prost(message, repeated, tag = "4")]
    pub usdtcontract_destroyed_black_funds: ::prost::alloc::vec::Vec<
        UsdtcontractDestroyedBlackFunds,
    >,
    #[prost(message, repeated, tag = "5")]
    pub usdtcontract_issues: ::prost::alloc::vec::Vec<UsdtcontractIssue>,
    #[prost(message, repeated, tag = "6")]
    pub usdtcontract_params: ::prost::alloc::vec::Vec<UsdtcontractParams>,
    #[prost(message, repeated, tag = "7")]
    pub usdtcontract_pauses: ::prost::alloc::vec::Vec<UsdtcontractPause>,
    #[prost(message, repeated, tag = "8")]
    pub usdtcontract_redeems: ::prost::alloc::vec::Vec<UsdtcontractRedeem>,
    #[prost(message, repeated, tag = "9")]
    pub usdtcontract_removed_black_lists: ::prost::alloc::vec::Vec<
        UsdtcontractRemovedBlackList,
    >,
    #[prost(message, repeated, tag = "10")]
    pub usdtcontract_transfers: ::prost::alloc::vec::Vec<UsdtcontractTransfer>,
    #[prost(message, repeated, tag = "11")]
    pub usdtcontract_unpauses: ::prost::alloc::vec::Vec<UsdtcontractUnpause>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Calls {
    #[prost(message, repeated, tag = "1")]
    pub usdtcontract_call_add_black_lists: ::prost::alloc::vec::Vec<
        UsdtcontractAddBlackListCall,
    >,
    #[prost(message, repeated, tag = "2")]
    pub usdtcontract_call_approves: ::prost::alloc::vec::Vec<UsdtcontractApproveCall>,
    #[prost(message, repeated, tag = "3")]
    pub usdtcontract_call_deprecates: ::prost::alloc::vec::Vec<
        UsdtcontractDeprecateCall,
    >,
    #[prost(message, repeated, tag = "4")]
    pub usdtcontract_call_destroy_black_funds: ::prost::alloc::vec::Vec<
        UsdtcontractDestroyBlackFundsCall,
    >,
    #[prost(message, repeated, tag = "5")]
    pub usdtcontract_call_issues: ::prost::alloc::vec::Vec<UsdtcontractIssueCall>,
    #[prost(message, repeated, tag = "6")]
    pub usdtcontract_call_pauses: ::prost::alloc::vec::Vec<UsdtcontractPauseCall>,
    #[prost(message, repeated, tag = "7")]
    pub usdtcontract_call_redeems: ::prost::alloc::vec::Vec<UsdtcontractRedeemCall>,
    #[prost(message, repeated, tag = "8")]
    pub usdtcontract_call_remove_black_lists: ::prost::alloc::vec::Vec<
        UsdtcontractRemoveBlackListCall,
    >,
    #[prost(message, repeated, tag = "9")]
    pub usdtcontract_call_set_params: ::prost::alloc::vec::Vec<
        UsdtcontractSetParamsCall,
    >,
    #[prost(message, repeated, tag = "10")]
    pub usdtcontract_call_transfers: ::prost::alloc::vec::Vec<UsdtcontractTransferCall>,
    #[prost(message, repeated, tag = "11")]
    pub usdtcontract_call_transfer_froms: ::prost::alloc::vec::Vec<
        UsdtcontractTransferFromCall,
    >,
    #[prost(message, repeated, tag = "12")]
    pub usdtcontract_call_transfer_ownerships: ::prost::alloc::vec::Vec<
        UsdtcontractTransferOwnershipCall,
    >,
    #[prost(message, repeated, tag = "13")]
    pub usdtcontract_call_unpauses: ::prost::alloc::vec::Vec<UsdtcontractUnpauseCall>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventsCalls {
    #[prost(message, optional, tag = "1")]
    pub events: ::core::option::Option<Events>,
    #[prost(message, optional, tag = "2")]
    pub calls: ::core::option::Option<Calls>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractAddedBlackList {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub u_user: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractApproval {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "7")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractDeprecate {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub new_address: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractDestroyedBlackFunds {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub u_black_listed_user: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "6")]
    pub u_balance: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractIssue {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(string, tag = "5")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractParams {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(string, tag = "5")]
    pub fee_basis_points: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub max_fee: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractPause {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractRedeem {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(string, tag = "5")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractRemovedBlackList {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub u_user: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractTransfer {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "7")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractUnpause {
    #[prost(string, tag = "1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub evt_index: u32,
    #[prost(message, optional, tag = "3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub evt_block_number: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractAddBlackListCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub u_evil_user: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractApproveCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub u_spender: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "7")]
    pub u_value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractDeprecateCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub u_upgraded_address: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractDestroyBlackFundsCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub u_black_listed_user: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractIssueCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(string, tag = "6")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractPauseCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractRedeemCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(string, tag = "6")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractRemoveBlackListCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub u_cleared_user: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractSetParamsCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(string, tag = "6")]
    pub new_basis_points: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub new_max_fee: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractTransferCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub u_to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "7")]
    pub u_value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractTransferFromCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub u_from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "7")]
    pub u_to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "8")]
    pub u_value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractTransferOwnershipCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub new_owner: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtcontractUnpauseCall {
    #[prost(string, tag = "1")]
    pub call_tx_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub call_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub call_block_number: u64,
    #[prost(uint64, tag = "4")]
    pub call_ordinal: u64,
    #[prost(bool, tag = "5")]
    pub call_success: bool,
}
