create table IF NOT EXISTS solana_raydium_transfer (
    id text primary key,
    signature text,
    block_time text,
    transaction_index text,
    funding_account text,
    recipient_account text,
    lamports text,
    funding_account_balance_pre_balance text,
    funding_account_balance_post_balance text,
    recipient_account_balance_pre_balance text,
    recipient_account_balance_post_balance text
);
create table IF NOT EXISTS solana_raydium_swap (
    id text primary key,
    signature text,
    block_time text,
    transaction_index text,
    amm text,
    user_swap text,
    mint_in text,
    mint_out text,
    amount_in text,
    amount_out text,
    direction text,
    pool_pc_amount text,
    pool_coin_amount text,
    pc_mint text,
    coin_mint text,
    user_pre_balance_in text,
    user_pre_balance_out text
);
create table IF NOT EXISTS solana_raydium_initialize (
    id text primary key,
    signature text,
    block_time bigint,
    block_number BIGINT,
    transaction_index text,
    amm text,
    initialize_user text,
    pc_init_amount BIGINT,
    coin_init_amount bigint,
    lp_init_amount bigint,
    pc_mint text,
    coin_mint text,
    lp_mint text,
    nonce bigint,
    market text,
    user_pc_pre_balance bigint,
    user_coin_pre_balance bigint
);
create table IF NOT EXISTS solana_raydium_deposite (
    id text primary key,
    signature text,
    block_time bigint,
    block_number BIGINT,
    transaction_index text,
    amm text,
    deposite_user text,
    pc_amount bigint,
    coin_amount bigint,
    lp_amount bigint,
    pc_mint text,
    coin_mint text,
    lp_mint text,
    pool_pc_amount bigint,
    pool_coin_amount bigint,
    pool_lp_amount bigint,
    user_pc_pre_balance bigint,
    user_coin_pre_balance bigint
);
create table IF NOT EXISTS solana_raydium_withdraw (
    id text primary key,
    signature text,
    block_time bigint,
    block_number BIGINT,
    transaction_index text,
    amm text,
    withdraw_user text,
    pc_amount bigint,
    coin_amount bigint,
    lp_amount bigint,
    pc_mint text,
    coin_mint text,
    lp_mint text,
    pool_pc_amount bigint,
    pool_coin_amount bigint,
    pool_lp_amount bigint,
    user_pc_pre_balance bigint,
    user_coin_pre_balance bigint
);
create table IF NOT EXISTS solana_raydium_withdraw_pnl (
    id text primary key,
    signature text,
    block_time bigint,
    block_number BIGINT,
    transaction_index text,
    amm text,
    withdraw_pnl_user text,
    pc_amount bigint,
    coin_amount bigint,
    pc_mint text,
    coin_mint text
);
create table IF NOT EXISTS solana_raydium_pump_fun_swap (
    id text primary key,
    signature text,
    block_time bigint,
    block_number BIGINT,
    transaction_index text,
    pump_fun_swap_user text,
    mint text,
    bonding_curve text,
    sol_amount bigint,
    token_amount bigint,
    direction text,
    virtual_sol_reserves bigint,
    virtual_token_reserves bigint,
    real_sol_reserves bigint,
    real_token_reserves bigint,
    user_token_pre_balance bigint
);
create table IF NOT EXISTS solana_raydium_pump_fun_withdraw (
    id text primary key,
    signature text,
    block_time bigint,
    block_number BIGINT,
    transaction_index text,
    mint text
);
create table IF NOT EXISTS solana_raydium_pump_fun_create (
    id text primary key,
    signature text,
    block_time bigint,
    block_number BIGINT,
    transaction_index text,
    fun_name text,
    symbol text,
    uri text,
    mint text,
    bonding_curve text,
    associated_bonding_curve text,
    metadata text
);